/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#ecf0ff",
        "background": "#f9f9ff",
        "on-tertiary-container": "#cadcec",
        "score-gold": "#C19C00",
        "on-background": "#091c35",
        "inverse-primary": "#a9c7ff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#dbe4eb",
        "primary-container": "#005eb8",
        "clinical-bg": "#F8FAFC",
        "surface-tint": "#005db6",
        "tertiary-container": "#50616e",
        "outline-variant": "#c2c6d4",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#a9c7ff",
        "secondary-fixed-dim": "#bfc8ce",
        "on-primary-container": "#c8daff",
        "on-tertiary-fixed-variant": "#384956",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#d6e3ff",
        "tertiary-fixed": "#d3e5f5",
        "surface-variant": "#d6e3ff",
        "on-secondary-container": "#5d666c",
        "surface-white": "#FFFFFF",
        "surface-dim": "#cadbfc",
        "error-container": "#ffdad6",
        "on-surface-variant": "#424752",
        "surface-bright": "#f9f9ff",
        "primary": "#00478d",
        "secondary": "#576066",
        "secondary-container": "#dbe4eb",
        "on-primary-fixed-variant": "#00468c",
        "success-green": "#107C10",
        "tertiary": "#394956",
        "on-secondary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3f484e",
        "surface-container": "#e7eeff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#141d22",
        "outline": "#727783",
        "on-tertiary-fixed": "#0c1d29",
        "tertiary-fixed-dim": "#b7c9d8",
        "on-surface": "#091c35",
        "primary-fixed": "#d6e3ff",
        "surface-container-high": "#dfe8ff",
        "inverse-surface": "#20314b",
        "on-primary-fixed": "#001b3d",
        "error-red": "#D13438",
        "surface": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "error": "#ba1a1a"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Manrope", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1rem',
        'full': '9999px',
      }
    },
  },
  plugins: [],
}
